version: '1'
# Define environments first
x-environments:
  dev-local: &dev-local-env
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:5000
      SERVER_NAME: localhost
      DNS_RESOLVER: 8.8.8.8
      SSL_CONFIG: ""

  dev-prod: &dev-prod-env
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://dronepilotapp.psi.ncsu.edu
      SERVER_NAME: localhost
      DNS_RESOLVER: 152.1.14.14 # points to NCSU DNS server (not needed if already on VPN/ currently not in use)
      SSL_CONFIG: ""

  prod: &prod-env
    environment:
      NODE_ENV: production
      # REACT_APP_API_URL: http://api:5000
      # DNS_RESOLVER: ""
      # SSL_CONFIG: ""

services:
  dev-local:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    <<: *dev-local-env
    profiles:
      - dev-local

  dev-prod:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    <<: *dev-prod-env
    profiles:
      - dev-prod

  prod:
    build:
      context: .
      dockerfile: dev.Dockerfile
      platforms:
        - "linux/amd64"
      args:
        # API_URL: http://api:5000
        # API_URL: http://192.168.1.254:5000
        # HOSTNAME: 192.168.1.254
        # API_URL: http://dronepilotapp.psi.ncsu.edu:5000
        API_URL: http://172.18.0.2:5000
        HOSTNAME: dronepilotapp.psi.ncsu.edu
        
    ports:
      - "80:80"
    networks:
      - drone-network
    <<: *prod-env
    profiles:
      - prod

networks:
  drone-network:
    external: true
