version: '3.8'

services:
  # Backend services
  api-dev:
    extends:
      file: ../drone-image_processing-api/docker-compose.yml
      service: api-dev
    profiles:
      - dev-local
  
  file-server:
    extends:
      file: ../drone-image_processing-api/docker-compose.yml
      service: file-server
    profiles:
      - dev-local
      - dev-prod
      - prod
  
  api-prod:
    extends:
      file: ../drone-image_processing-api/docker-compose.yml
      service: api-prod
    profiles:
      - prod
  
  # Frontend services
  frontend-dev-local:
    extends:
      file: ./docker-compose.yml
      service: frontend-dev-local
    profiles:
      - dev-local
    depends_on:
      - api-dev
      - file-server
  
  frontend-dev-prod:
    extends:
      file: ./docker-compose.yml
      service: frontend-dev-prod
    profiles:
      - dev-prod
    depends_on:
      - file-server
  
  frontend-prod:
    extends:
      file: ./docker-compose.yml
      service: frontend-prod
    profiles:
      - prod
    depends_on:
      - api-prod
      - file-server

networks:
  drone-network:
    name: drone-network