server {
    listen 80;
    
    # Route /data requests to file-server
    # location /data/ {
    #     proxy_pass http://localhost:8080/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
        
    #     # Let the proxied server handle CORS
    #     proxy_pass_request_headers on;
    # }
    # Route all other requests to api-dev
    # location / {
    #     proxy_pass http://api-dev:5000/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
        
    #     # Let the proxied server handle CORS
    #     proxy_pass_request_headers on;
    # }
    location /data {
        proxy_pass http://file-server:8080;
        rewrite ^/data(.*) $1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass_request_headers on;
    }
    
    # Proxy to the frontend Docker container
    # location / {
    #     proxy_pass http://127.0.0.1:8000;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_pass_request_headers on;
    # }

    # API endpoints - proxy directly to the API container
    # location ~ ^/(ping|flight-list|set-grid/.*) {
    #     include proxy_params;
    #     proxy_pass http://127.0.0.1:5000;
    #     # proxy_set_header Host $host;
    #     # proxy_set_header X-Real-IP $remote_addr;
    #     # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }
    location /ping {
        proxy_pass http://api-dev:5000;
    }
    location /flight-list {
        proxy_pass http://api-dev:5000;
    }
    location /set-grid {
        proxy_pass http://api-dev:5000;
    }
} 